### PR TITLE
More flexible interface, better tests, refactoring (was: embedStringDir support)

### PR DESCRIPTION
**Pull request by SASinestro**
This is just an extension of the more general functions provided for individual files already that covers the use case where a whole directory should be embedded as instances of another string-ish type instead of as a `ByteString`.

There is a fair bit of code duplication between the two 'sides', and it wouldn't be more than trivial to refactor it away either, in the obvious way it was done for `filePath'`; most (all? I wasn't thinking about this side too much as I wrote it) of it is just a matter of trivial replacements of `function :: Foo -> Bar` with `function' :: Foo -> Baz` to get the overall function's type to change from `outer :: Stuff -> Bar` to `outer :: Stuff -> Baz`.

I didn't want to put too much into one commit, though.

I'm going to investigate the possibility of just having there be the one interface and having it be always-polymorphic, as well. There might be a good reason not to (outside of needing to get people to stop using the `embedString*` family), but from where I'm sitting, it seems like the overhead should be ≈ 0 in any reasonable use case.

### CODE REVIEW

**Comment by snoyberg** [comment]
I'm not certain, but I think you'll find a major performance degradation with this in practice, due to likely creating a new `ByteString` on each evaluation of the value. More importantly, however, I do not believe this is a semantically good change: working this way will imply certain character encodings if you try to treat the file contents as `String` or `Text` values, and those assumptions will likely not be true in many cases.

**Comment by SASinestro** [comment]
I said it was just an investigation for a reason! I'm quite prepared for it to be a massive tire fire, but at the same time, I do feel that it's worth trying. Worst thing that happens is that I get to have some fun, right?

'Reasonable use case' is also a key phrase to keep in mind, since I imagine it might sting if there are no type annotations or if you're getting the file contents over and over for the same file.

For the first one, I'd guess it's Fairly Rare™ for it to be in a context where it's getting passed around as a generic `∀ a. IsString a` instead of either being type annotated at a global level or passed as an argument to an instance-specific function.

As for the second one... I think that's the sort of thing where you put up a big sign with a 🚫 symbol on it instead of worrying about the performance. It's pretty slow to read a file from disk or over the network over and over, too.

**Comment by SASinestro** [comment]
Don't look at this quite yet, I managed to eat some changes when I was fixing something with `git rebase`.

**Comment by SASinestro** [comment]
The removal of exported functions in 76f9cba seems like a big deal, but no one used them, so it's probably pretty okay.

* `getDir` is used by three actual projects on GitHub
    1. [travitch/foreign-inference](https://github.com/travitch/foreign-inference/blob/master/src/Foreign/Inference/Interface.hs)
         * Last commit was on Sep 7, 2014
    2. [MaxDaten/yage](https://github.com/MaxDaten/yage/blob/development/Main.hs)
        * Last commit was on Mar 19, 2015
        * 'CAUTION: code is [...] incorrect'
    3. [ekmett/quine](https://github.com/ekmett/quine/blob/master/tests/shaders.hs)
        * Last commit was on Jan 9, 2016
        * It's a self-declared 'toy project'
* `stringToBs` isn't used by anyone on GitHub
* `bsToExp` is used by four actual projects on GitHub, all of them just using it because it's around and easier than writing your own TH ByteString to expression converter.
    1. [elm-lang/elm-reactor](https://github.com/elm-lang/elm-reactor/blob/master/src/backend/StaticFiles.hs)
        * Active project
    2. [pikajude/jude.bio-servant](https://github.com/pikajude/jude.bio-servant/blob/everything-in-app/src/StaticFiles.hs)
        * Personal blog
    3. [charles-cooper/postgresql-query](https://github.com/charles-cooper/postgresql-query/blob/master/src/Database/PostgreSQL/Query/TH/SqlExp.hs)
    4. [MaxDaten/yage](https://github.com/MaxDaten/yage/blob/development/src/Yage/Rendering/Resources/GL/Shader.hs), again
        * Same caveats as before
* `strToExp` isn't used by anyone on GitHub

**Comment by SASinestro** [comment]
I have been thinking, occasionally, about the 'is this a good idea' part of the question while I've been working. 😉

At least as far as I can see it from here, it comes down to an issue of philosophy. 

The pure-polymorphic interface requires a little bit of care on the part of the end user; they have to select a type that works with the kind of file that they are accessing. Libraries should try to have defaults that are safe for people who don't already know everything, but allowing cleaner code for everyone while making the case of someone who either wants to embed a folder with mixed binary and text files or doesn't know what kind of file they have simply require following what would be best practices already doesn't seem like a huge tradeoff.

It's not like `ByteString`s are inherently perfect for data storage, they just happen to not be that opinionated. That's good, but "anything that quacks like an instance of IsString" is less opinionated still. For people who are using `ByteString`, there are no changes required in their code, and the only change everyone else will make is a simplification.

If there's a significant real-world speed penalty, everything changes, of course.

I don't know of any good practical examples of code that would show the performance of this branch. It's not obviously problematic in my testing, but considering that my testing has been the tiny test files and maybe 5kb of YAML in the app I wanted the feature that started this whole adventure, I don't think that I would have.

**Comment by mgsloan** [comment]
Thanks for working on this, but it would be more productive to ask first.  It's a really bad idea to use `StringL` and `IsString`, lots of compile-time overhead.  Easy mistake to make, see this issue - https://github.com/bennofs/th-lift-instances/issues/4

It seems like all of that, and the new forked package, could be avoided by using the following utility

```
polyFileEmbed :: FilePath -> Q Exp
polyFileEmbed fp = [e| fromString $(fileEmbed fp) |]
```

Why not just define that utility instead of breaking the API?  Not sure if this belongs in the API either, it makes it easier for users to write inefficient code.

**Comment by SASinestro** [comment]
I have no realistic expectation of this code actually getting merged as it is, it was just a case of ‘I wonder if this would make things simpler?’ getting worked on for something to do. Like I said, purely an experiment in how to make ~~things worse in every way~~ a potentially universal API instead of the 'two mostly identical versions' situation in the real version.

I hope there’s a useful idea in there somewhere. I feel kind of weird about uploading the fork, to be honest, but it works well in the specific case I’m using it for (mostly because as I said, it’s tiny files and not that many of them) and it’s nice to be able to just have it ‘do the right thing’ in context.

> Why not just define that utility instead of breaking the API?

Yeah, that’s probably a substantially better solution than all of this mess, plus the appropriate tweaks. 

That seems like a better way to do the original API than all of the duplication that’s there now, although there’s probably good reasons why that hasn’t been done, either.

**Pull request closed without merging**
