### PR TITLE
Add build system agnostic version of makeRelativeToProject

### PR DESCRIPTION
**Pull request by aveltras**
Hi !
I had to fork this to be able to make the package work with the Bazel build system (which doesn't use cabal files at all).
Hope this can be upstreamed.

### CODE REVIEW

**Comment by snoyberg** [comment]
Seems OK. I’d prefer a more descriptive name. Also, please add Haddocks, a since comment, a minor version bump, and a changelog entry.

**Comment by aveltras** [comment]
Should be good now. 
Tell me if the function name is OK for you.

**Review by snoyberg — APPROVED** [review]
LGTM!

**Comment by snoyberg** [comment]
I'll merge/release after CI passes.

**Pull request merged**
